package com.grivo.service;

import com.grivo.entity.Agreement;
import org.springframework.stereotype.Service;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

/**
 * Generates a formal, ready-to-file deposit complaint letter.
 *
 * IMPORTANT SCOPE NOTE: this deliberately does NOT try to give
 * state-specific legal citations we can't fully verify (tenancy law
 * varies by state and changes over time). Instead it points to the
 * nationally-available, always-valid route — the Consumer Protection Act,
 * 2019, via the District Consumer Disputes Redressal Commission — which
 * covers "deficiency in service" claims like a landlord wrongfully
 * withholding a deposit, in every state, regardless of whether that
 * state has separately adopted the Model Tenancy Act.
 *
 * This is explicitly informational, not legal advice — the generated
 * letter says so, and a real user should still consult a lawyer for
 * anything contested or high-value.
 */
@Service
public class ComplaintTemplateService {

    private static final DateTimeFormatter DATE_FMT = DateTimeFormatter.ofPattern("dd MMMM yyyy");

    public String generateComplaintLetter(Agreement agreement, String disputeDescription) {
        String tenantName = agreement.getTenant().getName();
        String landlordName = agreement.getLandlord().getName();
        String address = agreement.getProperty().getAddressLine() + ", " + agreement.getProperty().getCity()
                + ", " + agreement.getProperty().getState();
        String moveInDate = agreement.getMoveInDate().format(DATE_FMT);
        String moveOutDate = agreement.getMoveOutDate() != null
                ? agreement.getMoveOutDate().format(DATE_FMT) : "[move-out date not recorded]";
        String today = LocalDate.now().format(DATE_FMT);

        return """
                FORMAL COMPLAINT — SECURITY DEPOSIT DISPUTE

                Date: %s

                To,
                %s
                (Landlord)

                Subject: Demand for return of security deposit — %s

                Dear %s,

                I am writing regarding the rental property at %s, which I occupied
                as a tenant from %s to %s under our rental agreement.

                As per the terms of our agreement, I paid a security deposit of
                ₹%.2f. I am formally requesting the return of this deposit, less
                any deductions that are lawfully justified and supported by evidence.

                Details of my dispute:
                %s

                I have retained timestamped, geotagged photographic evidence of the
                property's condition at both move-in and move-out, which is available
                to support this claim.

                I request a response within 15 days of this letter. If the deposit is
                not returned or a satisfactory resolution is not reached, I intend to
                pursue this matter with the District Consumer Disputes Redressal
                Commission under the Consumer Protection Act, 2019, which covers
                deficiency-of-service claims of this nature, or with the appropriate
                Rent Authority in %s if one has been notified in this state.

                Regards,
                %s
                (Tenant)

                ---
                NOTE: This letter was generated by Grivo as an informational starting
                point based on the details in your agreement and dispute. It is not
                legal advice. Please review it carefully and consult a lawyer before
                relying on it for a high-value or contested dispute.
                """.formatted(
                today, landlordName, address, landlordName, address, moveInDate, moveOutDate,
                agreement.getDepositAmount(), disputeDescription, agreement.getProperty().getState(), tenantName
        );
    }
}
